version: '3'
services:
  mysql:
    volumes:
      - './docker/data/db:/var/lib/mysql'

  nginx:
    volumes:
      - './app/public/:/usr/src/app/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - ${NGINX_PORT}:80

  php:
    volumes:
      - './app/:/usr/src/app'
    env_file:
      - .env

  phpmyadmin:
    ports:
      - ${PHPMYADMIN_PORT}:80

